import { _PacketRegistry } from "./PacketRegistry";

export class _v480 extends _PacketRegistry {

    constructor() {
        super(480);
        this._CLIENT_SPAWN_OBJECT = 0x00;
        this._CLIENT_SPAWN_EXPERIENCE_ORB = 0x01;
        this._CLIENT_SPAWN_GLOBAL_ENTITY = 0x02;
        this._CLIENT_SPAWN_MOB = 0x03;
        this._CLIENT_SPAWN_PAINTING = 0x04;
        this._CLIENT_SPAWN_PLAYER = 0x05;
        this._CLIENT_ANIMATION = 0x06;
        this._CLIENT_STATISTICS = 0x07;
        this._CLIENT_BLOCK_BREAK_ANIMATION = 0x08;
        this._CLIENT_UPDATE_BLOCK_ENTITY = 0x09;
        this._CLIENT_BLOCK_ACTION = 0x0A;
        this._CLIENT_BLOCK_CHANGE = 0x0B;
        this._CLIENT_BOSS_BAR = 0x0C;
        this._CLIENT_DIFFICULTY = 0x0D;
        this._CLIENT_CHAT = 0x0E;
        this._CLIENT_MULTI_BLOCK_CHANGE = 0x0F;
        this._CLIENT_TAB_COMPLETE = 0x10;
        this._CLIENT_DECLARE_COMMANDS = 0x11;
        this._CLIENT_CONFIRM_TRANSACTION = 0x12;
        this._CLIENT_CLOSE_WINDOW = 0x13;
        this._CLIENT_WINDOW_ITEMS = 0x14;
        this._CLIENT_WINDOW_PROPERTY = 0x15;
        this._CLIENT_SET_SLOT = 0x16;
        this._CLIENT_SET_COOLDOWN = 0x17;
        this._CLIENT_PLUGIN_MESSAGE = 0x18;
        this._CLIENT_NAMED_SOUND_EFFECT = 0x19;
        this._CLIENT_DISCONNECT = 0x1A;
        this._CLIENT_ENTITY_STATUS = 0x1B;
        this._CLIENT_EXPLOSION = 0x1C;
        this._CLIENT_UNLOAD_CHUNK = 0x1D;
        this._CLIENT_CHANGE_GAME_STATE = 0x1E;
        this._CLIENT_OPEN_HORSE_WINDOW = 0x1F; // new
        this._CLIENT_KEEPALIVE = 0x20;
        this._CLIENT_CHUNK_DATA = 0x21;
        this._CLIENT_EFFECT = 0x22;
        this._CLIENT_PARTICLE = 0x23;
        this._CLIENT_UPDATE_LIGHT = 0x24; // new
        this._CLIENT_JOIN_GAME = 0x25;
        this._CLIENT_MAPS = 0x26;
        this._CLIENT_TRADE_LIST = 0x27; // new
        this._CLIENT_ENTITY_RELATIVE_MOVE = 0x28;
        this._CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE = 0x29;
        this._CLIENT_ENTITY_LOOK = 0x2A;
        this._CLIENT_ENTITY = 0x2B;
        this._CLIENT_VEHICLE_MOVE = 0x2C;
        this._CLIENT_OPEN_BOOK = 0x2D; // new
        this._CLIENT_OPEN_WINDOW = 0x2E;
        this._CLIENT_SIGN_EDITOR_OPEN = 0x2F;
        this._CLIENT_CRAFT_RECIPE_RESPONSE = 0x30;
        this._CLIENT_PLAYER_ABILITIES = 0x31;
        this._CLIENT_COMBAT_EVENT = 0x32;
        this._CLIENT_PLAYER_LIST = 0x33;
        this._CLIENT_FACE_PLAYER = 0x34;
        this._CLIENT_PLAYER_POSITION_AND_LOOK = 0x35;
        this._CLIENT_UNLOCK_RECIPES = 0x36;
        this._CLIENT_DESTROY_ENTITIES = 0x37;
        this._CLIENT_REMOVE_ENTITY_EFFECT = 0x38;
        this._CLIENT_RESOURCE_PACK = 0x39;
        this._CLIENT_RESPAWN = 0x3A;
        this._CLIENT_ENTITY_HEAD_LOOK = 0x3B;
        this._CLIENT_ADVANCEMENT_PROGRESS = 0x3C;
        this._CLIENT_WORLD_BORDER = 0x3D;
        this._CLIENT_CAMERA = 0x3E;
        this._CLIENT_HELD_ITEM_CHANGE = 0x3F;
        this._CLIENT_UPDATE_VIEW_POSITION = 0x40; // new
        this._CLIENT_UPDATE_VIEW_DISTANCE = 0x41; // new
        this._CLIENT_DISPLAY_SCOREBOARD = 0x42;
        this._CLIENT_ENTITY_METADATA = 0x43;
        this._CLIENT_ATTACH_ENTITY = 0x44;
        this._CLIENT_ENTITY_VELOCITY = 0x45;
        this._CLIENT_ENTITY_EQUIPMENT = 0x46;
        this._CLIENT_SET_EXPERIENCE = 0x47;
        this._CLIENT_UPDATE_HEALTH = 0x48;
        this._CLIENT_SCOREBOARD_OBJECTIVE = 0x49;
        this._CLIENT_SET_PASSENGERS = 0x4A;
        this._CLIENT_TEAMS = 0x4B;
        this._CLIENT_UPDATE_SCORE = 0x4C;
        this._CLIENT_SPAWN_POSITION = 0x4D;
        this._CLIENT_TIME_UPDATE = 0x4E;
        this._CLIENT_TITLE = 0x4F;
        this._CLIENT_ENTITY_SOUND_EFFECT = 0x50; // new
        this._CLIENT_SOUND_EFFECT = 0x51;
        this._CLIENT_STOP_SOUND = 0x52;
        this._CLIENT_PLAYER_LIST_HEAD_FOOT = 0x53;
        this._CLIENT_NBT_QUERY_RESPONSE = 0x54;
        this._CLIENT_COLLECT_ITEM = 0x55;
        this._CLIENT_ENTITY_TELEPORT = 0x56;
        this._CLIENT_ADVANCEMENTS = 0x57;
        this._CLIENT_ENTITY_PROPERTIES = 0x58;
        this._CLIENT_ENTITY_EFFECT = 0x59;
        this._CLIENT_DECLARE_RECIPES = 0x5A;
        this._CLIENT_TAGS = 0x5B;
        this._CLIENT_UPDATE_SIGN = -1;
        this._CLIENT_MAP_CHUNK_BULK = -1;
        this._CLIENT_SET_COMPRESSION = -1;
        this._CLIENT_UPDATE_ENTITY_NBT = -1;
        this._CLIENT_USE_BED = -1; // removed

        this._SERVER_TELEPORT_CONFIRM = 0x00;
        this._SERVER_QUERY_BLOCK_NBT = 0x01;
        this._SERVER_SET_DIFFICULTY = 0x02; // new
        this._SERVER_CHAT = 0x03;
        this._SERVER_CLIENT_STATUS = 0x04;
        this._SERVER_CLIENT_SETTINGS = 0x05;
        this._SERVER_TAB_COMPLETE = 0x06;
        this._SERVER_CONFIRM_TRANSACTION = 0x07;
        this._SERVER_ENCHANT_ITEM = 0x08;
        this._SERVER_CLICK_WINDOW = 0x09;
        this._SERVER_CLOSE_WINDOW = 0x0A;
        this._SERVER_PLUGIN_MESSAGE = 0x0B;
        this._SERVER_EDIT_BOOK = 0x0C;
        this._SERVER_QUERY_ENTITY_NBT = 0x0D;
        this._SERVER_USE_ENTITY = 0x0E;
        this._SERVER_KEEPALIVE = 0x0F;
        this._SERVER_LOCK_DIFFICULTY = 0x10; // new
        this._SERVER_PLAYER_POSITION = 0x11;
        this._SERVER_PLAYER_LOOK_AND_POSITION = 0x12;
        this._SERVER_PLAYER_LOOK = 0x13;
        this._SERVER_PLAYER = 0x14;
        this._SERVER_VEHICLE_MOVE = 0x15;
        this._SERVER_STEER_BOAT = 0x16;
        this._SERVER_PICK_ITEM = 0x17;
        this._SERVER_CRAFT_RECIPE_REQUEST = 0x18;
        this._SERVER_PLAYER_ABILITIES = 0x19;
        this._SERVER_PLAYER_DIGGING = 0x1A;
        this._SERVER_ENTITY_ACTION = 0x1B;
        this._SERVER_STEER_VEHICLE = 0x1C;
        this._SERVER_CRAFTING_BOOK_DATA = 0x1D;
        this._SERVER_NAME_ITEM = 0x1E;
        this._SERVER_RESOURCE_PACK_STATUS = 0x1F;
        this._SERVER_ADVANCEMENT_TAB = 0x20;
        this._SERVER_SELECT_TRADE = 0x21;
        this._SERVER_SET_BEACON_EFFECT = 0x22;
        this._SERVER_HELD_ITEM_CHANGE = 0x23;
        this._SERVER_UPDATE_COMMAND_BLOCK = 0x24;
        this._SERVER_UPDATE_COMMAND_BLOCK_MINECART = 0x25;
        this._SERVER_CREATIVE_INVENTORY_ACTION = 0x26;
        this._SERVER_UPDATE_JIGSAW_BLOCK = 0x27; // new
        this._SERVER_UPDATE_STRUCTURE_BLOCK = 0x28;
        this._SERVER_UPDATE_SIGN = 0x29;
        this._SERVER_ANIMATION = 0x2A;
        this._SERVER_SPECTATE = 0x2B;
        this._SERVER_PLAYER_BLOCK_PLACEMENT = 0x2C;
        this._SERVER_USE_ITEM = 0x2D;
        this._SERVER_PREPARE_CRAFTING_GRID = -1;

    }
}
