import { _BlockRegistry } from "./BlockRegistry";
import { _LeavesBlock, _PistonBlock, _BlockPistonExtension, _SandBlock, _GrassBlock, _DeadBushBlock, _GrassBushBlock, _FlowerBlock } from "./Blocks";
import { _Block } from "./Block";

export class _BlocksHelper {
    public _AIR: _Block | undefined;
    public _STONE: _Block | undefined;
    public _GRANITE: _Block | undefined;
    public _POLISHED_GRANITE: _Block | undefined;
    public _DIORITE: _Block | undefined;
    public _POLISHED_DIORITE: _Block | undefined;
    public _ANDESITE: _Block | undefined;
    public _POLISHED_ANDESITE: _Block | undefined;
    public _GRASS_BLOCK: _Block | undefined;
    public _DIRT: _Block | undefined;
    public _COARSE_DIRT: _Block | undefined;
    public _PODZOL: _Block | undefined;
    public _COBBLESTONE: _Block | undefined;
    public _OAK_PLANKS: _Block | undefined;
    public _SPRUCE_PLANKS: _Block | undefined;
    public _BIRCH_PLANKS: _Block | undefined;
    public _JUNGLE_PLANKS: _Block | undefined;
    public _ACACIA_PLANKS: _Block | undefined;
    public _DARK_OAK_PLANKS: _Block | undefined;
    public _OAK_SAPLING: _Block | undefined;
    public _SPRUCE_SAPLING: _Block | undefined;
    public _BIRCH_SAPLING: _Block | undefined;
    public _JUNGLE_SAPLING: _Block | undefined;
    public _ACACIA_SAPLING: _Block | undefined;
    public _DARK_OAK_SAPLING: _Block | undefined;
    public _BEDROCK: _Block | undefined;
    public _WATER: _Block | undefined;
    public _LAVA: _Block | undefined;
    public _SAND: _Block | undefined;
    public _RED_SAND: _Block | undefined;
    public _GRAVEL: _Block | undefined;
    public _GOLD_ORE: _Block | undefined;
    public _IRON_ORE: _Block | undefined;
    public _COAL_ORE: _Block | undefined;
    public _OAK_LOG: _Block | undefined;
    public _SPRUCE_LOG: _Block | undefined;
    public _BIRCH_LOG: _Block | undefined;
    public _JUNGLE_LOG: _Block | undefined;
    public _ACACIA_LOG: _Block | undefined;
    public _DARK_OAK_LOG: _Block | undefined;
    public _STRIPPED_SPRUCE_LOG: _Block | undefined;
    public _STRIPPED_BIRCH_LOG: _Block | undefined;
    public _STRIPPED_JUNGLE_LOG: _Block | undefined;
    public _STRIPPED_ACACIA_LOG: _Block | undefined;
    public _STRIPPED_DARK_OAK_LOG: _Block | undefined;
    public _STRIPPED_OAK_LOG: _Block | undefined;
    public _OAK_WOOD: _Block | undefined;
    public _SPRUCE_WOOD: _Block | undefined;
    public _BIRCH_WOOD: _Block | undefined;
    public _JUNGLE_WOOD: _Block | undefined;
    public _ACACIA_WOOD: _Block | undefined;
    public _DARK_OAK_WOOD: _Block | undefined;
    public _STRIPPED_OAK_WOOD: _Block | undefined;
    public _STRIPPED_SPRUCE_WOOD: _Block | undefined;
    public _STRIPPED_BIRCH_WOOD: _Block | undefined;
    public _STRIPPED_JUNGLE_WOOD: _Block | undefined;
    public _STRIPPED_ACACIA_WOOD: _Block | undefined;
    public _STRIPPED_DARK_OAK_WOOD: _Block | undefined;
    public _OAK_LEAVES: _Block | undefined;
    public _SPRUCE_LEAVES: _Block | undefined;
    public _BIRCH_LEAVES: _Block | undefined;
    public _JUNGLE_LEAVES: _Block | undefined;
    public _ACACIA_LEAVES: _Block | undefined;
    public _DARK_OAK_LEAVES: _Block | undefined;
    public _SPONGE: _Block | undefined;
    public _WET_SPONGE: _Block | undefined;
    public _GLASS: _Block | undefined;
    public _LAPIS_ORE: _Block | undefined;
    public _LAPIS_BLOCK: _Block | undefined;
    public _DISPENSER: _Block | undefined;
    public _SANDSTONE: _Block | undefined;
    public _CHISELED_SANDSTONE: _Block | undefined;
    public _CUT_SANDSTONE: _Block | undefined;
    public _NOTE_BLOCK: _Block | undefined;
    public _WHITE_BED: _Block | undefined;
    public _ORANGE_BED: _Block | undefined;
    public _MAGENTA_BED: _Block | undefined;
    public _LIGHT_BLUE_BED: _Block | undefined;
    public _YELLOW_BED: _Block | undefined;
    public _LIME_BED: _Block | undefined;
    public _PINK_BED: _Block | undefined;
    public _GRAY_BED: _Block | undefined;
    public _LIGHT_GRAY_BED: _Block | undefined;
    public _CYAN_BED: _Block | undefined;
    public _PURPLE_BED: _Block | undefined;
    public _BLUE_BED: _Block | undefined;
    public _BROWN_BED: _Block | undefined;
    public _GREEN_BED: _Block | undefined;
    public _RED_BED: _Block | undefined;
    public _BLACK_BED: _Block | undefined;
    public _POWERED_RAIL: _Block | undefined;
    public _DETECTOR_RAIL: _Block | undefined;
    public _STICKY_PISTON: _Block | undefined;
    public _COBWEB: _Block | undefined;
    public _GRASS: _Block | undefined;
    public _FERN: _Block | undefined;
    public _DEAD_BUSH: _Block | undefined;
    public _SEAGRASS: _Block | undefined;
    public _TALL_SEAGRASS: _Block | undefined;
    public _PISTON: _Block | undefined;
    public _PISTON_HEAD: _Block | undefined;
    public _WHITE_WOOL: _Block | undefined;
    public _ORANGE_WOOL: _Block | undefined;
    public _MAGENTA_WOOL: _Block | undefined;
    public _LIGHT_BLUE_WOOL: _Block | undefined;
    public _YELLOW_WOOL: _Block | undefined;
    public _LIME_WOOL: _Block | undefined;
    public _PINK_WOOL: _Block | undefined;
    public _GRAY_WOOL: _Block | undefined;
    public _LIGHT_GRAY_WOOL: _Block | undefined;
    public _CYAN_WOOL: _Block | undefined;
    public _PURPLE_WOOL: _Block | undefined;
    public _BLUE_WOOL: _Block | undefined;
    public _BROWN_WOOL: _Block | undefined;
    public _GREEN_WOOL: _Block | undefined;
    public _RED_WOOL: _Block | undefined;
    public _BLACK_WOOL: _Block | undefined;
    public _MOVING_PISTON: _Block | undefined;
    public _DANDELION: _Block | undefined;
    public _POPPY: _Block | undefined;
    public _BLUE_ORCHID: _Block | undefined;
    public _ALLIUM: _Block | undefined;
    public _AZURE_BLUET: _Block | undefined;
    public _RED_TULIP: _Block | undefined;
    public _ORANGE_TULIP: _Block | undefined;
    public _WHITE_TULIP: _Block | undefined;
    public _PINK_TULIP: _Block | undefined;
    public _OXEYE_DAISY: _Block | undefined;
    public _CORNFLOWER: _Block | undefined;
    public _WITHER_ROSE: _Block | undefined;
    public _LILY_OF_THE_VALLEY: _Block | undefined;
    public _BROWN_MUSHROOM: _Block | undefined;
    public _RED_MUSHROOM: _Block | undefined;
    public _GOLD_BLOCK: _Block | undefined;
    public _IRON_BLOCK: _Block | undefined;
    public _BRICKS: _Block | undefined;
    public _TNT: _Block | undefined;
    public _BOOKSHELF: _Block | undefined;
    public _MOSSY_COBBLESTONE: _Block | undefined;
    public _OBSIDIAN: _Block | undefined;
    public _TORCH: _Block | undefined;
    public _WALL_TORCH: _Block | undefined;
    public _FIRE: _Block | undefined;
    public _SPAWNER: _Block | undefined;
    public _OAK_STAIRS: _Block | undefined;
    public _CHEST: _Block | undefined;
    public _REDSTONE_WIRE: _Block | undefined;
    public _DIAMOND_ORE: _Block | undefined;
    public _DIAMOND_BLOCK: _Block | undefined;
    public _CRAFTING_TABLE: _Block | undefined;
    public _WHEAT: _Block | undefined;
    public _FARMLAND: _Block | undefined;
    public _FURNACE: _Block | undefined;
    public _OAK_SIGN: _Block | undefined;
    public _SPRUCE_SIGN: _Block | undefined;
    public _BIRCH_SIGN: _Block | undefined;
    public _ACACIA_SIGN: _Block | undefined;
    public _JUNGLE_SIGN: _Block | undefined;
    public _DARK_OAK_SIGN: _Block | undefined;
    public _OAK_DOOR: _Block | undefined;
    public _LADDER: _Block | undefined;
    public _RAIL: _Block | undefined;
    public _COBBLESTONE_STAIRS: _Block | undefined;
    public _OAK_WALL_SIGN: _Block | undefined;
    public _SPRUCE_WALL_SIGN: _Block | undefined;
    public _BIRCH_WALL_SIGN: _Block | undefined;
    public _ACACIA_WALL_SIGN: _Block | undefined;
    public _JUNGLE_WALL_SIGN: _Block | undefined;
    public _DARK_OAK_WALL_SIGN: _Block | undefined;
    public _LEVER: _Block | undefined;
    public _STONE_PRESSURE_PLATE: _Block | undefined;
    public _IRON_DOOR: _Block | undefined;
    public _OAK_PRESSURE_PLATE: _Block | undefined;
    public _SPRUCE_PRESSURE_PLATE: _Block | undefined;
    public _BIRCH_PRESSURE_PLATE: _Block | undefined;
    public _JUNGLE_PRESSURE_PLATE: _Block | undefined;
    public _ACACIA_PRESSURE_PLATE: _Block | undefined;
    public _DARK_OAK_PRESSURE_PLATE: _Block | undefined;
    public _REDSTONE_ORE: _Block | undefined;
    public _REDSTONE_TORCH: _Block | undefined;
    public _REDSTONE_WALL_TORCH: _Block | undefined;
    public _STONE_BUTTON: _Block | undefined;
    public _SNOW: _Block | undefined;
    public _ICE: _Block | undefined;
    public _SNOW_BLOCK: _Block | undefined;
    public _CACTUS: _Block | undefined;
    public _CLAY: _Block | undefined;
    public _SUGAR_CANE: _Block | undefined;
    public _JUKEBOX: _Block | undefined;
    public _OAK_FENCE: _Block | undefined;
    public _PUMPKIN: _Block | undefined;
    public _NETHERRACK: _Block | undefined;
    public _SOUL_SAND: _Block | undefined;
    public _GLOWSTONE: _Block | undefined;
    public _NETHER_PORTAL: _Block | undefined;
    public _CARVED_PUMPKIN: _Block | undefined;
    public _JACK_O_LANTERN: _Block | undefined;
    public _CAKE: _Block | undefined;
    public _REPEATER: _Block | undefined;
    public _WHITE_STAINED_GLASS: _Block | undefined;
    public _ORANGE_STAINED_GLASS: _Block | undefined;
    public _MAGENTA_STAINED_GLASS: _Block | undefined;
    public _LIGHT_BLUE_STAINED_GLASS: _Block | undefined;
    public _YELLOW_STAINED_GLASS: _Block | undefined;
    public _LIME_STAINED_GLASS: _Block | undefined;
    public _PINK_STAINED_GLASS: _Block | undefined;
    public _GRAY_STAINED_GLASS: _Block | undefined;
    public _LIGHT_GRAY_STAINED_GLASS: _Block | undefined;
    public _CYAN_STAINED_GLASS: _Block | undefined;
    public _PURPLE_STAINED_GLASS: _Block | undefined;
    public _BLUE_STAINED_GLASS: _Block | undefined;
    public _BROWN_STAINED_GLASS: _Block | undefined;
    public _GREEN_STAINED_GLASS: _Block | undefined;
    public _RED_STAINED_GLASS: _Block | undefined;
    public _BLACK_STAINED_GLASS: _Block | undefined;
    public _OAK_TRAPDOOR: _Block | undefined;
    public _SPRUCE_TRAPDOOR: _Block | undefined;
    public _BIRCH_TRAPDOOR: _Block | undefined;
    public _JUNGLE_TRAPDOOR: _Block | undefined;
    public _ACACIA_TRAPDOOR: _Block | undefined;
    public _DARK_OAK_TRAPDOOR: _Block | undefined;
    public _STONE_BRICKS: _Block | undefined;
    public _MOSSY_STONE_BRICKS: _Block | undefined;
    public _CRACKED_STONE_BRICKS: _Block | undefined;
    public _CHISELED_STONE_BRICKS: _Block | undefined;
    public _INFESTED_STONE: _Block | undefined;
    public _INFESTED_COBBLESTONE: _Block | undefined;
    public _INFESTED_STONE_BRICKS: _Block | undefined;
    public _INFESTED_MOSSY_STONE_BRICKS: _Block | undefined;
    public _INFESTED_CRACKED_STONE_BRICKS: _Block | undefined;
    public _INFESTED_CHISELED_STONE_BRICKS: _Block | undefined;
    public _BROWN_MUSHROOM_BLOCK: _Block | undefined;
    public _RED_MUSHROOM_BLOCK: _Block | undefined;
    public _MUSHROOM_STEM: _Block | undefined;
    public _IRON_BARS: _Block | undefined;
    public _GLASS_PANE: _Block | undefined;
    public _MELON: _Block | undefined;
    public _ATTACHED_PUMPKIN_STEM: _Block | undefined;
    public _ATTACHED_MELON_STEM: _Block | undefined;
    public _PUMPKIN_STEM: _Block | undefined;
    public _MELON_STEM: _Block | undefined;
    public _VINE: _Block | undefined;
    public _OAK_FENCE_GATE: _Block | undefined;
    public _BRICK_STAIRS: _Block | undefined;
    public _STONE_BRICK_STAIRS: _Block | undefined;
    public _MYCELIUM: _Block | undefined;
    public _LILY_PAD: _Block | undefined;
    public _NETHER_BRICKS: _Block | undefined;
    public _NETHER_BRICK_FENCE: _Block | undefined;
    public _NETHER_BRICK_STAIRS: _Block | undefined;
    public _NETHER_WART: _Block | undefined;
    public _ENCHANTING_TABLE: _Block | undefined;
    public _BREWING_STAND: _Block | undefined;
    public _CAULDRON: _Block | undefined;
    public _END_PORTAL: _Block | undefined;
    public _END_PORTAL_FRAME: _Block | undefined;
    public _END_STONE: _Block | undefined;
    public _DRAGON_EGG: _Block | undefined;
    public _REDSTONE_LAMP: _Block | undefined;
    public _COCOA: _Block | undefined;
    public _SANDSTONE_STAIRS: _Block | undefined;
    public _EMERALD_ORE: _Block | undefined;
    public _ENDER_CHEST: _Block | undefined;
    public _TRIPWIRE_HOOK: _Block | undefined;
    public _TRIPWIRE: _Block | undefined;
    public _EMERALD_BLOCK: _Block | undefined;
    public _SPRUCE_STAIRS: _Block | undefined;
    public _BIRCH_STAIRS: _Block | undefined;
    public _JUNGLE_STAIRS: _Block | undefined;
    public _COMMAND_BLOCK: _Block | undefined;
    public _BEACON: _Block | undefined;
    public _COBBLESTONE_WALL: _Block | undefined;
    public _MOSSY_COBBLESTONE_WALL: _Block | undefined;
    public _FLOWER_POT: _Block | undefined;
    public _POTTED_OAK_SAPLING: _Block | undefined;
    public _POTTED_SPRUCE_SAPLING: _Block | undefined;
    public _POTTED_BIRCH_SAPLING: _Block | undefined;
    public _POTTED_JUNGLE_SAPLING: _Block | undefined;
    public _POTTED_ACACIA_SAPLING: _Block | undefined;
    public _POTTED_DARK_OAK_SAPLING: _Block | undefined;
    public _POTTED_FERN: _Block | undefined;
    public _POTTED_DANDELION: _Block | undefined;
    public _POTTED_POPPY: _Block | undefined;
    public _POTTED_BLUE_ORCHID: _Block | undefined;
    public _POTTED_ALLIUM: _Block | undefined;
    public _POTTED_AZURE_BLUET: _Block | undefined;
    public _POTTED_RED_TULIP: _Block | undefined;
    public _POTTED_ORANGE_TULIP: _Block | undefined;
    public _POTTED_WHITE_TULIP: _Block | undefined;
    public _POTTED_PINK_TULIP: _Block | undefined;
    public _POTTED_OXEYE_DAISY: _Block | undefined;
    public _POTTED_CORNFLOWER: _Block | undefined;
    public _POTTED_LILY_OF_THE_VALLEY: _Block | undefined;
    public _POTTED_WITHER_ROSE: _Block | undefined;
    public _POTTED_RED_MUSHROOM: _Block | undefined;
    public _POTTED_BROWN_MUSHROOM: _Block | undefined;
    public _POTTED_DEAD_BUSH: _Block | undefined;
    public _POTTED_CACTUS: _Block | undefined;
    public _CARROTS: _Block | undefined;
    public _POTATOES: _Block | undefined;
    public _OAK_BUTTON: _Block | undefined;
    public _SPRUCE_BUTTON: _Block | undefined;
    public _BIRCH_BUTTON: _Block | undefined;
    public _JUNGLE_BUTTON: _Block | undefined;
    public _ACACIA_BUTTON: _Block | undefined;
    public _DARK_OAK_BUTTON: _Block | undefined;
    public _SKELETON_SKULL: _Block | undefined;
    public _SKELETON_WALL_SKULL: _Block | undefined;
    public _WITHER_SKELETON_SKULL: _Block | undefined;
    public _WITHER_SKELETON_WALL_SKULL: _Block | undefined;
    public _ZOMBIE_HEAD: _Block | undefined;
    public _ZOMBIE_WALL_HEAD: _Block | undefined;
    public _PLAYER_HEAD: _Block | undefined;
    public _PLAYER_WALL_HEAD: _Block | undefined;
    public _CREEPER_HEAD: _Block | undefined;
    public _CREEPER_WALL_HEAD: _Block | undefined;
    public _DRAGON_HEAD: _Block | undefined;
    public _DRAGON_WALL_HEAD: _Block | undefined;
    public _ANVIL: _Block | undefined;
    public _CHIPPED_ANVIL: _Block | undefined;
    public _DAMAGED_ANVIL: _Block | undefined;
    public _TRAPPED_CHEST: _Block | undefined;
    public _LIGHT_WEIGHTED_PRESSURE_PLATE: _Block | undefined;
    public _HEAVY_WEIGHTED_PRESSURE_PLATE: _Block | undefined;
    public _COMPARATOR: _Block | undefined;
    public _DAYLIGHT_DETECTOR: _Block | undefined;
    public _REDSTONE_BLOCK: _Block | undefined;
    public _NETHER_QUARTZ_ORE: _Block | undefined;
    public _HOPPER: _Block | undefined;
    public _QUARTZ_BLOCK: _Block | undefined;
    public _CHISELED_QUARTZ_BLOCK: _Block | undefined;
    public _QUARTZ_PILLAR: _Block | undefined;
    public _QUARTZ_STAIRS: _Block | undefined;
    public _ACTIVATOR_RAIL: _Block | undefined;
    public _DROPPER: _Block | undefined;
    public _WHITE_TERRACOTTA: _Block | undefined;
    public _ORANGE_TERRACOTTA: _Block | undefined;
    public _MAGENTA_TERRACOTTA: _Block | undefined;
    public _LIGHT_BLUE_TERRACOTTA: _Block | undefined;
    public _YELLOW_TERRACOTTA: _Block | undefined;
    public _LIME_TERRACOTTA: _Block | undefined;
    public _PINK_TERRACOTTA: _Block | undefined;
    public _GRAY_TERRACOTTA: _Block | undefined;
    public _LIGHT_GRAY_TERRACOTTA: _Block | undefined;
    public _CYAN_TERRACOTTA: _Block | undefined;
    public _PURPLE_TERRACOTTA: _Block | undefined;
    public _BLUE_TERRACOTTA: _Block | undefined;
    public _BROWN_TERRACOTTA: _Block | undefined;
    public _GREEN_TERRACOTTA: _Block | undefined;
    public _RED_TERRACOTTA: _Block | undefined;
    public _BLACK_TERRACOTTA: _Block | undefined;
    public _WHITE_STAINED_GLASS_PANE: _Block | undefined;
    public _ORANGE_STAINED_GLASS_PANE: _Block | undefined;
    public _MAGENTA_STAINED_GLASS_PANE: _Block | undefined;
    public _LIGHT_BLUE_STAINED_GLASS_PANE: _Block | undefined;
    public _YELLOW_STAINED_GLASS_PANE: _Block | undefined;
    public _LIME_STAINED_GLASS_PANE: _Block | undefined;
    public _PINK_STAINED_GLASS_PANE: _Block | undefined;
    public _GRAY_STAINED_GLASS_PANE: _Block | undefined;
    public _LIGHT_GRAY_STAINED_GLASS_PANE: _Block | undefined;
    public _CYAN_STAINED_GLASS_PANE: _Block | undefined;
    public _PURPLE_STAINED_GLASS_PANE: _Block | undefined;
    public _BLUE_STAINED_GLASS_PANE: _Block | undefined;
    public _BROWN_STAINED_GLASS_PANE: _Block | undefined;
    public _GREEN_STAINED_GLASS_PANE: _Block | undefined;
    public _RED_STAINED_GLASS_PANE: _Block | undefined;
    public _BLACK_STAINED_GLASS_PANE: _Block | undefined;
    public _ACACIA_STAIRS: _Block | undefined;
    public _DARK_OAK_STAIRS: _Block | undefined;
    public _SLIME_BLOCK: _Block | undefined;
    public _BARRIER: _Block | undefined;
    public _IRON_TRAPDOOR: _Block | undefined;
    public _PRISMARINE: _Block | undefined;
    public _PRISMARINE_BRICKS: _Block | undefined;
    public _DARK_PRISMARINE: _Block | undefined;
    public _PRISMARINE_STAIRS: _Block | undefined;
    public _PRISMARINE_BRICK_STAIRS: _Block | undefined;
    public _DARK_PRISMARINE_STAIRS: _Block | undefined;
    public _PRISMARINE_SLAB: _Block | undefined;
    public _PRISMARINE_BRICK_SLAB: _Block | undefined;
    public _DARK_PRISMARINE_SLAB: _Block | undefined;
    public _SEA_LANTERN: _Block | undefined;
    public _HAY_BLOCK: _Block | undefined;
    public _WHITE_CARPET: _Block | undefined;
    public _ORANGE_CARPET: _Block | undefined;
    public _MAGENTA_CARPET: _Block | undefined;
    public _LIGHT_BLUE_CARPET: _Block | undefined;
    public _YELLOW_CARPET: _Block | undefined;
    public _LIME_CARPET: _Block | undefined;
    public _PINK_CARPET: _Block | undefined;
    public _GRAY_CARPET: _Block | undefined;
    public _LIGHT_GRAY_CARPET: _Block | undefined;
    public _CYAN_CARPET: _Block | undefined;
    public _PURPLE_CARPET: _Block | undefined;
    public _BLUE_CARPET: _Block | undefined;
    public _BROWN_CARPET: _Block | undefined;
    public _GREEN_CARPET: _Block | undefined;
    public _RED_CARPET: _Block | undefined;
    public _BLACK_CARPET: _Block | undefined;
    public _TERRACOTTA: _Block | undefined;
    public _COAL_BLOCK: _Block | undefined;
    public _PACKED_ICE: _Block | undefined;
    public _SUNFLOWER: _Block | undefined;
    public _LILAC: _Block | undefined;
    public _ROSE_BUSH: _Block | undefined;
    public _PEONY: _Block | undefined;
    public _TALL_GRASS: _Block | undefined;
    public _LARGE_FERN: _Block | undefined;
    public _WHITE_BANNER: _Block | undefined;
    public _ORANGE_BANNER: _Block | undefined;
    public _MAGENTA_BANNER: _Block | undefined;
    public _LIGHT_BLUE_BANNER: _Block | undefined;
    public _YELLOW_BANNER: _Block | undefined;
    public _LIME_BANNER: _Block | undefined;
    public _PINK_BANNER: _Block | undefined;
    public _GRAY_BANNER: _Block | undefined;
    public _LIGHT_GRAY_BANNER: _Block | undefined;
    public _CYAN_BANNER: _Block | undefined;
    public _PURPLE_BANNER: _Block | undefined;
    public _BLUE_BANNER: _Block | undefined;
    public _BROWN_BANNER: _Block | undefined;
    public _GREEN_BANNER: _Block | undefined;
    public _RED_BANNER: _Block | undefined;
    public _BLACK_BANNER: _Block | undefined;
    public _WHITE_WALL_BANNER: _Block | undefined;
    public _ORANGE_WALL_BANNER: _Block | undefined;
    public _MAGENTA_WALL_BANNER: _Block | undefined;
    public _LIGHT_BLUE_WALL_BANNER: _Block | undefined;
    public _YELLOW_WALL_BANNER: _Block | undefined;
    public _LIME_WALL_BANNER: _Block | undefined;
    public _PINK_WALL_BANNER: _Block | undefined;
    public _GRAY_WALL_BANNER: _Block | undefined;
    public _LIGHT_GRAY_WALL_BANNER: _Block | undefined;
    public _CYAN_WALL_BANNER: _Block | undefined;
    public _PURPLE_WALL_BANNER: _Block | undefined;
    public _BLUE_WALL_BANNER: _Block | undefined;
    public _BROWN_WALL_BANNER: _Block | undefined;
    public _GREEN_WALL_BANNER: _Block | undefined;
    public _RED_WALL_BANNER: _Block | undefined;
    public _BLACK_WALL_BANNER: _Block | undefined;
    public _RED_SANDSTONE: _Block | undefined;
    public _CHISELED_RED_SANDSTONE: _Block | undefined;
    public _CUT_RED_SANDSTONE: _Block | undefined;
    public _RED_SANDSTONE_STAIRS: _Block | undefined;
    public _OAK_SLAB: _Block | undefined;
    public _SPRUCE_SLAB: _Block | undefined;
    public _BIRCH_SLAB: _Block | undefined;
    public _JUNGLE_SLAB: _Block | undefined;
    public _ACACIA_SLAB: _Block | undefined;
    public _DARK_OAK_SLAB: _Block | undefined;
    public _STONE_SLAB: _Block | undefined;
    public _SMOOTH_STONE_SLAB: _Block | undefined;
    public _SANDSTONE_SLAB: _Block | undefined;
    public _CUT_SANDSTONE_SLAB: _Block | undefined;
    public _PETRIFIED_OAK_SLAB: _Block | undefined;
    public _COBBLESTONE_SLAB: _Block | undefined;
    public _BRICK_SLAB: _Block | undefined;
    public _STONE_BRICK_SLAB: _Block | undefined;
    public _NETHER_BRICK_SLAB: _Block | undefined;
    public _QUARTZ_SLAB: _Block | undefined;
    public _RED_SANDSTONE_SLAB: _Block | undefined;
    public _CUT_RED_SANDSTONE_SLAB: _Block | undefined;
    public _PURPUR_SLAB: _Block | undefined;
    public _SMOOTH_STONE: _Block | undefined;
    public _SMOOTH_SANDSTONE: _Block | undefined;
    public _SMOOTH_QUARTZ: _Block | undefined;
    public _SMOOTH_RED_SANDSTONE: _Block | undefined;
    public _SPRUCE_FENCE_GATE: _Block | undefined;
    public _BIRCH_FENCE_GATE: _Block | undefined;
    public _JUNGLE_FENCE_GATE: _Block | undefined;
    public _ACACIA_FENCE_GATE: _Block | undefined;
    public _DARK_OAK_FENCE_GATE: _Block | undefined;
    public _SPRUCE_FENCE: _Block | undefined;
    public _BIRCH_FENCE: _Block | undefined;
    public _JUNGLE_FENCE: _Block | undefined;
    public _ACACIA_FENCE: _Block | undefined;
    public _DARK_OAK_FENCE: _Block | undefined;
    public _SPRUCE_DOOR: _Block | undefined;
    public _BIRCH_DOOR: _Block | undefined;
    public _JUNGLE_DOOR: _Block | undefined;
    public _ACACIA_DOOR: _Block | undefined;
    public _DARK_OAK_DOOR: _Block | undefined;
    public _END_ROD: _Block | undefined;
    public _CHORUS_PLANT: _Block | undefined;
    public _CHORUS_FLOWER: _Block | undefined;
    public _PURPUR_BLOCK: _Block | undefined;
    public _PURPUR_PILLAR: _Block | undefined;
    public _PURPUR_STAIRS: _Block | undefined;
    public _END_STONE_BRICKS: _Block | undefined;
    public _BEETROOTS: _Block | undefined;
    public _GRASS_PATH: _Block | undefined;
    public _END_GATEWAY: _Block | undefined;
    public _REPEATING_COMMAND_BLOCK: _Block | undefined;
    public _CHAIN_COMMAND_BLOCK: _Block | undefined;
    public _FROSTED_ICE: _Block | undefined;
    public _MAGMA_BLOCK: _Block | undefined;
    public _NETHER_WART_BLOCK: _Block | undefined;
    public _RED_NETHER_BRICKS: _Block | undefined;
    public _BONE_BLOCK: _Block | undefined;
    public _STRUCTURE_VOID: _Block | undefined;
    public _OBSERVER: _Block | undefined;
    public _SHULKER_BOX: _Block | undefined;
    public _WHITE_SHULKER_BOX: _Block | undefined;
    public _ORANGE_SHULKER_BOX: _Block | undefined;
    public _MAGENTA_SHULKER_BOX: _Block | undefined;
    public _LIGHT_BLUE_SHULKER_BOX: _Block | undefined;
    public _YELLOW_SHULKER_BOX: _Block | undefined;
    public _LIME_SHULKER_BOX: _Block | undefined;
    public _PINK_SHULKER_BOX: _Block | undefined;
    public _GRAY_SHULKER_BOX: _Block | undefined;
    public _LIGHT_GRAY_SHULKER_BOX: _Block | undefined;
    public _CYAN_SHULKER_BOX: _Block | undefined;
    public _PURPLE_SHULKER_BOX: _Block | undefined;
    public _BLUE_SHULKER_BOX: _Block | undefined;
    public _BROWN_SHULKER_BOX: _Block | undefined;
    public _GREEN_SHULKER_BOX: _Block | undefined;
    public _RED_SHULKER_BOX: _Block | undefined;
    public _BLACK_SHULKER_BOX: _Block | undefined;
    public _WHITE_GLAZED_TERRACOTTA: _Block | undefined;
    public _ORANGE_GLAZED_TERRACOTTA: _Block | undefined;
    public _MAGENTA_GLAZED_TERRACOTTA: _Block | undefined;
    public _LIGHT_BLUE_GLAZED_TERRACOTTA: _Block | undefined;
    public _YELLOW_GLAZED_TERRACOTTA: _Block | undefined;
    public _LIME_GLAZED_TERRACOTTA: _Block | undefined;
    public _PINK_GLAZED_TERRACOTTA: _Block | undefined;
    public _GRAY_GLAZED_TERRACOTTA: _Block | undefined;
    public _LIGHT_GRAY_GLAZED_TERRACOTTA: _Block | undefined;
    public _CYAN_GLAZED_TERRACOTTA: _Block | undefined;
    public _PURPLE_GLAZED_TERRACOTTA: _Block | undefined;
    public _BLUE_GLAZED_TERRACOTTA: _Block | undefined;
    public _BROWN_GLAZED_TERRACOTTA: _Block | undefined;
    public _GREEN_GLAZED_TERRACOTTA: _Block | undefined;
    public _RED_GLAZED_TERRACOTTA: _Block | undefined;
    public _BLACK_GLAZED_TERRACOTTA: _Block | undefined;
    public _WHITE_CONCRETE: _Block | undefined;
    public _ORANGE_CONCRETE: _Block | undefined;
    public _MAGENTA_CONCRETE: _Block | undefined;
    public _LIGHT_BLUE_CONCRETE: _Block | undefined;
    public _YELLOW_CONCRETE: _Block | undefined;
    public _LIME_CONCRETE: _Block | undefined;
    public _PINK_CONCRETE: _Block | undefined;
    public _GRAY_CONCRETE: _Block | undefined;
    public _LIGHT_GRAY_CONCRETE: _Block | undefined;
    public _CYAN_CONCRETE: _Block | undefined;
    public _PURPLE_CONCRETE: _Block | undefined;
    public _BLUE_CONCRETE: _Block | undefined;
    public _BROWN_CONCRETE: _Block | undefined;
    public _GREEN_CONCRETE: _Block | undefined;
    public _RED_CONCRETE: _Block | undefined;
    public _BLACK_CONCRETE: _Block | undefined;
    public _WHITE_CONCRETE_POWDER: _Block | undefined;
    public _ORANGE_CONCRETE_POWDER: _Block | undefined;
    public _MAGENTA_CONCRETE_POWDER: _Block | undefined;
    public _LIGHT_BLUE_CONCRETE_POWDER: _Block | undefined;
    public _YELLOW_CONCRETE_POWDER: _Block | undefined;
    public _LIME_CONCRETE_POWDER: _Block | undefined;
    public _PINK_CONCRETE_POWDER: _Block | undefined;
    public _GRAY_CONCRETE_POWDER: _Block | undefined;
    public _LIGHT_GRAY_CONCRETE_POWDER: _Block | undefined;
    public _CYAN_CONCRETE_POWDER: _Block | undefined;
    public _PURPLE_CONCRETE_POWDER: _Block | undefined;
    public _BLUE_CONCRETE_POWDER: _Block | undefined;
    public _BROWN_CONCRETE_POWDER: _Block | undefined;
    public _GREEN_CONCRETE_POWDER: _Block | undefined;
    public _RED_CONCRETE_POWDER: _Block | undefined;
    public _BLACK_CONCRETE_POWDER: _Block | undefined;
    public _KELP: _Block | undefined;
    public _KELP_PLANT: _Block | undefined;
    public _DRIED_KELP_BLOCK: _Block | undefined;
    public _TURTLE_EGG: _Block | undefined;
    public _DEAD_TUBE_CORAL_BLOCK: _Block | undefined;
    public _DEAD_BRAIN_CORAL_BLOCK: _Block | undefined;
    public _DEAD_BUBBLE_CORAL_BLOCK: _Block | undefined;
    public _DEAD_FIRE_CORAL_BLOCK: _Block | undefined;
    public _DEAD_HORN_CORAL_BLOCK: _Block | undefined;
    public _TUBE_CORAL_BLOCK: _Block | undefined;
    public _BRAIN_CORAL_BLOCK: _Block | undefined;
    public _BUBBLE_CORAL_BLOCK: _Block | undefined;
    public _FIRE_CORAL_BLOCK: _Block | undefined;
    public _HORN_CORAL_BLOCK: _Block | undefined;
    public _DEAD_TUBE_CORAL: _Block | undefined;
    public _DEAD_BRAIN_CORAL: _Block | undefined;
    public _DEAD_BUBBLE_CORAL: _Block | undefined;
    public _DEAD_FIRE_CORAL: _Block | undefined;
    public _DEAD_HORN_CORAL: _Block | undefined;
    public _TUBE_CORAL: _Block | undefined;
    public _BRAIN_CORAL: _Block | undefined;
    public _BUBBLE_CORAL: _Block | undefined;
    public _FIRE_CORAL: _Block | undefined;
    public _HORN_CORAL: _Block | undefined;
    public _DEAD_TUBE_CORAL_FAN: _Block | undefined;
    public _DEAD_BRAIN_CORAL_FAN: _Block | undefined;
    public _DEAD_BUBBLE_CORAL_FAN: _Block | undefined;
    public _DEAD_FIRE_CORAL_FAN: _Block | undefined;
    public _DEAD_HORN_CORAL_FAN: _Block | undefined;
    public _TUBE_CORAL_FAN: _Block | undefined;
    public _BRAIN_CORAL_FAN: _Block | undefined;
    public _BUBBLE_CORAL_FAN: _Block | undefined;
    public _FIRE_CORAL_FAN: _Block | undefined;
    public _HORN_CORAL_FAN: _Block | undefined;
    public _DEAD_TUBE_CORAL_WALL_FAN: _Block | undefined;
    public _DEAD_BRAIN_CORAL_WALL_FAN: _Block | undefined;
    public _DEAD_BUBBLE_CORAL_WALL_FAN: _Block | undefined;
    public _DEAD_FIRE_CORAL_WALL_FAN: _Block | undefined;
    public _DEAD_HORN_CORAL_WALL_FAN: _Block | undefined;
    public _TUBE_CORAL_WALL_FAN: _Block | undefined;
    public _BRAIN_CORAL_WALL_FAN: _Block | undefined;
    public _BUBBLE_CORAL_WALL_FAN: _Block | undefined;
    public _FIRE_CORAL_WALL_FAN: _Block | undefined;
    public _HORN_CORAL_WALL_FAN: _Block | undefined;
    public _SEA_PICKLE: _Block | undefined;
    public _BLUE_ICE: _Block | undefined;
    public _CONDUIT: _Block | undefined;
    public _BAMBOO_SAPLING: _Block | undefined;
    public _BAMBOO: _Block | undefined;
    public _POTTED_BAMBOO: _Block | undefined;
    public _VOID_AIR: _Block | undefined;
    public _CAVE_AIR: _Block | undefined;
    public _BUBBLE_COLUMN: _Block | undefined;
    public _POLISHED_GRANITE_STAIRS: _Block | undefined;
    public _SMOOTH_RED_SANDSTONE_STAIRS: _Block | undefined;
    public _MOSSY_STONE_BRICK_STAIRS: _Block | undefined;
    public _POLISHED_DIORITE_STAIRS: _Block | undefined;
    public _MOSSY_COBBLESTONE_STAIRS: _Block | undefined;
    public _END_STONE_BRICK_STAIRS: _Block | undefined;
    public _STONE_STAIRS: _Block | undefined;
    public _SMOOTH_SANDSTONE_STAIRS: _Block | undefined;
    public _SMOOTH_QUARTZ_STAIRS: _Block | undefined;
    public _GRANITE_STAIRS: _Block | undefined;
    public _ANDESITE_STAIRS: _Block | undefined;
    public _RED_NETHER_BRICK_STAIRS: _Block | undefined;
    public _POLISHED_ANDESITE_STAIRS: _Block | undefined;
    public _DIORITE_STAIRS: _Block | undefined;
    public _POLISHED_GRANITE_SLAB: _Block | undefined;
    public _SMOOTH_RED_SANDSTONE_SLAB: _Block | undefined;
    public _MOSSY_STONE_BRICK_SLAB: _Block | undefined;
    public _POLISHED_DIORITE_SLAB: _Block | undefined;
    public _MOSSY_COBBLESTONE_SLAB: _Block | undefined;
    public _END_STONE_BRICK_SLAB: _Block | undefined;
    public _SMOOTH_SANDSTONE_SLAB: _Block | undefined;
    public _SMOOTH_QUARTZ_SLAB: _Block | undefined;
    public _GRANITE_SLAB: _Block | undefined;
    public _ANDESITE_SLAB: _Block | undefined;
    public _RED_NETHER_BRICK_SLAB: _Block | undefined;
    public _POLISHED_ANDESITE_SLAB: _Block | undefined;
    public _DIORITE_SLAB: _Block | undefined;
    public _BRICK_WALL: _Block | undefined;
    public _PRISMARINE_WALL: _Block | undefined;
    public _RED_SANDSTONE_WALL: _Block | undefined;
    public _MOSSY_STONE_BRICK_WALL: _Block | undefined;
    public _GRANITE_WALL: _Block | undefined;
    public _STONE_BRICK_WALL: _Block | undefined;
    public _NETHER_BRICK_WALL: _Block | undefined;
    public _ANDESITE_WALL: _Block | undefined;
    public _RED_NETHER_BRICK_WALL: _Block | undefined;
    public _SANDSTONE_WALL: _Block | undefined;
    public _END_STONE_BRICK_WALL: _Block | undefined;
    public _DIORITE_WALL: _Block | undefined;
    public _SCAFFOLDING: _Block | undefined;
    public _LOOM: _Block | undefined;
    public _BARREL: _Block | undefined;
    public _SMOKER: _Block | undefined;
    public _BLAST_FURNACE: _Block | undefined;
    public _CARTOGRAPHY_TABLE: _Block | undefined;
    public _FLETCHING_TABLE: _Block | undefined;
    public _GRINDSTONE: _Block | undefined;
    public _LECTERN: _Block | undefined;
    public _SMITHING_TABLE: _Block | undefined;
    public _STONECUTTER: _Block | undefined;
    public _BELL: _Block | undefined;
    public _LANTERN: _Block | undefined;
    public _CAMPFIRE: _Block | undefined;
    public _SWEET_BERRY_BUSH: _Block | undefined;
    public _STRUCTURE_BLOCK: _Block | undefined;
    public _JIGSAW: _Block | undefined;
    public _COMPOSTER: _Block | undefined;
    /*
    constructor(registry: _BlockRegistry) {
        const getRegisteredBlock = (name: string) => {
            return <_Block>registry._blocksByName.get(name);
        };
        this._air = getRegisteredBlock("air");
        this._stone = getRegisteredBlock("stone");
        this._grass = <_GrassBlock>getRegisteredBlock("grass");
        this._dirt = getRegisteredBlock("dirt");
        this._cobblestone = getRegisteredBlock("cobblestone");
        this._planks = getRegisteredBlock("planks");
        this._sapling = getRegisteredBlock("sapling");
        this._bedrock = getRegisteredBlock("bedrock");
        // this._flowing_water = <_BlockDynamicLiquid>getRegisteredBlock("flowing_water");
        // this._water = <_BlockStaticLiquid>getRegisteredBlock("water");
        // this._flowing_lava = <_BlockDynamicLiquid>getRegisteredBlock("flowing_lava");
        // this._lava = <_BlockStaticLiquid>getRegisteredBlock("lava");
        this._sand = <_SandBlock>getRegisteredBlock("sand");
        this._gravel = getRegisteredBlock("gravel");
        this._gold_ore = getRegisteredBlock("gold_ore");
        this._iron_ore = getRegisteredBlock("iron_ore");
        this._coal_ore = getRegisteredBlock("coal_ore");
        this._log = getRegisteredBlock("log");
        this._log2 = getRegisteredBlock("log2");
        this._leaves = <_LeavesBlock>getRegisteredBlock("leaves");
        this._leaves2 = <_LeavesBlock>getRegisteredBlock("leaves2");
        this._sponge = getRegisteredBlock("sponge");
        this._glass = getRegisteredBlock("glass");
        this._lapis_ore = getRegisteredBlock("lapis_ore");
        this._lapis_block = getRegisteredBlock("lapis_block");
        this._dispenser = getRegisteredBlock("dispenser");
        this._sandstone = getRegisteredBlock("sandstone");
        this._noteblock = getRegisteredBlock("noteblock");
        this._bed = getRegisteredBlock("bed");
        this._golden_rail = getRegisteredBlock("golden_rail");
        this._detector_rail = getRegisteredBlock("detector_rail");
        this._sticky_piston = <_PistonBlock>getRegisteredBlock("sticky_piston");
        this._web = getRegisteredBlock("web");
        this._grassbush = <_GrassBushBlock>getRegisteredBlock("grass");
        this._deadbush = <_DeadBushBlock>getRegisteredBlock("deadbush");
        this._piston = <_PistonBlock>getRegisteredBlock("piston");
        this._piston_head = <_BlockPistonExtension>getRegisteredBlock("piston_head");
        this._wool = getRegisteredBlock("wool");
        // this._piston_extension = <_BlockPistonMoving>getRegisteredBlock("piston_extension");
        this._yellow_flower = <_FlowerBlock>getRegisteredBlock("yellow_flower");
        this._red_flower = <_FlowerBlock>getRegisteredBlock("red_flower");
        // this._brown_mushroom = <_BlockBush>getRegisteredBlock("brown_mushroom");
        // this._red_mushroom = <_BlockBush>getRegisteredBlock("red_mushroom");
        this._gold_block = getRegisteredBlock("gold_block");
        this._iron_block = getRegisteredBlock("iron_block");
        /*
        this._double_stone_slab = (BlockSlab)getRegisteredBlock("double_stone_slab");
        this._stone_slab = (BlockSlab)getRegisteredBlock("stone_slab");
        this._brick_block = getRegisteredBlock("brick_block");
        this._tnt = getRegisteredBlock("tnt");
        this._bookshelf = getRegisteredBlock("bookshelf");
        this._mossy_cobblestone = getRegisteredBlock("mossy_cobblestone");
        this._obsidian = getRegisteredBlock("obsidian");
        this._torch = getRegisteredBlock("torch");
        this._fire = (BlockFire)getRegisteredBlock("fire");
        this._mob_spawner = getRegisteredBlock("mob_spawner");
        this._oak_stairs = getRegisteredBlock("oak_stairs");
        this._chest = (BlockChest)getRegisteredBlock("chest");
        this._redstone_wire = (BlockRedstoneWire)getRegisteredBlock("redstone_wire");
        this._diamond_ore = getRegisteredBlock("diamond_ore");
        this._diamond_block = getRegisteredBlock("diamond_block");
        this._crafting_table = getRegisteredBlock("crafting_table");
        this._wheat = getRegisteredBlock("wheat");
        this._farmland = getRegisteredBlock("farmland");
        this._furnace = getRegisteredBlock("furnace");
        this._lit_furnace = getRegisteredBlock("lit_furnace");
        this._standing_sign = getRegisteredBlock("standing_sign");
        this._oak_door = getRegisteredBlock("wooden_door");
        this._spruce_door = getRegisteredBlock("spruce_door");
        this._birch_door = getRegisteredBlock("birch_door");
        this._jungle_door = getRegisteredBlock("jungle_door");
        this._acacia_door = getRegisteredBlock("acacia_door");
        this._dark_oak_door = getRegisteredBlock("dark_oak_door");
        this._ladder = getRegisteredBlock("ladder");
        this._rail = getRegisteredBlock("rail");
        this._stone_stairs = getRegisteredBlock("stone_stairs");
        this._wall_sign = getRegisteredBlock("wall_sign");
        this._lever = getRegisteredBlock("lever");
        this._stone_pressure_plate = getRegisteredBlock("stone_pressure_plate");
        this._iron_door = getRegisteredBlock("iron_door");
        this._wooden_pressure_plate = getRegisteredBlock("wooden_pressure_plate");
        this._redstone_ore = getRegisteredBlock("redstone_ore");
        this._lit_redstone_ore = getRegisteredBlock("lit_redstone_ore");
        this._unlit_redstone_torch = getRegisteredBlock("unlit_redstone_torch");
        this._redstone_torch = getRegisteredBlock("redstone_torch");
        this._stone_button = getRegisteredBlock("stone_button");
        this._snow_layer = getRegisteredBlock("snow_layer");
        this._ice = getRegisteredBlock("ice");
        this._snow = getRegisteredBlock("snow");
        this._cactus = (BlockCactus)getRegisteredBlock("cactus");
        this._clay = getRegisteredBlock("clay");
        this._reeds = (BlockReed)getRegisteredBlock("reeds");
        this._jukebox = getRegisteredBlock("jukebox");
        this._oak_fence = getRegisteredBlock("fence");
        this._spruce_fence = getRegisteredBlock("spruce_fence");
        this._birch_fence = getRegisteredBlock("birch_fence");
        this._jungle_fence = getRegisteredBlock("jungle_fence");
        this._dark_oak_fence = getRegisteredBlock("dark_oak_fence");
        this._acacia_fence = getRegisteredBlock("acacia_fence");
        this._pumpkin = getRegisteredBlock("pumpkin");
        this._netherrack = getRegisteredBlock("netherrack");
        this._soul_sand = getRegisteredBlock("soul_sand");
        this._glowstone = getRegisteredBlock("glowstone");
        this._portal = (BlockPortal)getRegisteredBlock("portal");
        this._lit_pumpkin = getRegisteredBlock("lit_pumpkin");
        this._cake = getRegisteredBlock("cake");
        this._unpowered_repeater = (BlockRedstoneRepeater)getRegisteredBlock("unpowered_repeater");
        this._powered_repeater = (BlockRedstoneRepeater)getRegisteredBlock("powered_repeater");
        this._trapdoor = getRegisteredBlock("trapdoor");
        this._monster_egg = getRegisteredBlock("monster_egg");
        this._stonebrick = getRegisteredBlock("stonebrick");
        this._brown_mushroom_block = getRegisteredBlock("brown_mushroom_block");
        this._red_mushroom_block = getRegisteredBlock("red_mushroom_block");
        this._iron_bars = getRegisteredBlock("iron_bars");
        this._glass_pane = getRegisteredBlock("glass_pane");
        this._melon_block = getRegisteredBlock("melon_block");
        this._pumpkin_stem = getRegisteredBlock("pumpkin_stem");
        this._melon_stem = getRegisteredBlock("melon_stem");
        this._vine = getRegisteredBlock("vine");
        this._oak_fence_gate = getRegisteredBlock("fence_gate");
        this._spruce_fence_gate = getRegisteredBlock("spruce_fence_gate");
        this._birch_fence_gate = getRegisteredBlock("birch_fence_gate");
        this._jungle_fence_gate = getRegisteredBlock("jungle_fence_gate");
        this._dark_oak_fence_gate = getRegisteredBlock("dark_oak_fence_gate");
        this._acacia_fence_gate = getRegisteredBlock("acacia_fence_gate");
        this._brick_stairs = getRegisteredBlock("brick_stairs");
        this._stone_brick_stairs = getRegisteredBlock("stone_brick_stairs");
        this._mycelium = (BlockMycelium)getRegisteredBlock("mycelium");
        this._waterlily = getRegisteredBlock("waterlily");
        this._nether_brick = getRegisteredBlock("nether_brick");
        this._nether_brick_fence = getRegisteredBlock("nether_brick_fence");
        this._nether_brick_stairs = getRegisteredBlock("nether_brick_stairs");
        this._nether_wart = getRegisteredBlock("nether_wart");
        this._enchanting_table = getRegisteredBlock("enchanting_table");
        this._brewing_stand = getRegisteredBlock("brewing_stand");
        this._cauldron = (BlockCauldron)getRegisteredBlock("cauldron");
        this._end_portal = getRegisteredBlock("end_portal");
        this._end_portal_frame = getRegisteredBlock("end_portal_frame");
        this._end_stone = getRegisteredBlock("end_stone");
        this._dragon_egg = getRegisteredBlock("dragon_egg");
        this._redstone_lamp = getRegisteredBlock("redstone_lamp");
        this._lit_redstone_lamp = getRegisteredBlock("lit_redstone_lamp");
        this._double_wooden_slab = (BlockSlab)getRegisteredBlock("double_wooden_slab");
        this._wooden_slab = (BlockSlab)getRegisteredBlock("wooden_slab");
        this._cocoa = getRegisteredBlock("cocoa");
        this._sandstone_stairs = getRegisteredBlock("sandstone_stairs");
        this._emerald_ore = getRegisteredBlock("emerald_ore");
        this._ender_chest = getRegisteredBlock("ender_chest");
        this._tripwire_hook = (BlockTripWireHook)getRegisteredBlock("tripwire_hook");
        this._tripwire = getRegisteredBlock("tripwire");
        this._emerald_block = getRegisteredBlock("emerald_block");
        this._spruce_stairs = getRegisteredBlock("spruce_stairs");
        this._birch_stairs = getRegisteredBlock("birch_stairs");
        this._jungle_stairs = getRegisteredBlock("jungle_stairs");
        this._command_block = getRegisteredBlock("command_block");
        this._beacon = (BlockBeacon)getRegisteredBlock("beacon");
        this._cobblestone_wall = getRegisteredBlock("cobblestone_wall");
        this._flower_pot = getRegisteredBlock("flower_pot");
        this._carrots = getRegisteredBlock("carrots");
        this._potatoes = getRegisteredBlock("potatoes");
        this._wooden_button = getRegisteredBlock("wooden_button");
        this._skull = (BlockSkull)getRegisteredBlock("skull");
        this._anvil = getRegisteredBlock("anvil");
        this._trapped_chest = getRegisteredBlock("trapped_chest");
        this._light_weighted_pressure_plate = getRegisteredBlock("light_weighted_pressure_plate");
        this._heavy_weighted_pressure_plate = getRegisteredBlock("heavy_weighted_pressure_plate");
        this._unpowered_comparator = (BlockRedstoneComparator)getRegisteredBlock("unpowered_comparator");
        this._powered_comparator = (BlockRedstoneComparator)getRegisteredBlock("powered_comparator");
        this._daylight_detector = (BlockDaylightDetector)getRegisteredBlock("daylight_detector");
        this._daylight_detector_inverted = (BlockDaylightDetector)getRegisteredBlock("daylight_detector_inverted");
        this._redstone_block = getRegisteredBlock("redstone_block");
        this._quartz_ore = getRegisteredBlock("quartz_ore");
        this._hopper = (BlockHopper)getRegisteredBlock("hopper");
        this._quartz_block = getRegisteredBlock("quartz_block");
        this._quartz_stairs = getRegisteredBlock("quartz_stairs");
        this._activator_rail = getRegisteredBlock("activator_rail");
        this._dropper = getRegisteredBlock("dropper");
        this._stained_hardened_clay = getRegisteredBlock("stained_hardened_clay");
        this._barrier = getRegisteredBlock("barrier");
        this._iron_trapdoor = getRegisteredBlock("iron_trapdoor");
        this._hay_block = getRegisteredBlock("hay_block");
        this._carpet = getRegisteredBlock("carpet");
        this._hardened_clay = getRegisteredBlock("hardened_clay");
        this._coal_block = getRegisteredBlock("coal_block");
        this._packed_ice = getRegisteredBlock("packed_ice");
        this._acacia_stairs = getRegisteredBlock("acacia_stairs");
        this._dark_oak_stairs = getRegisteredBlock("dark_oak_stairs");
        this._slime_block = getRegisteredBlock("slime");
        this._double_plant = (BlockDoublePlant)getRegisteredBlock("double_plant");
        this._stained_glass = (BlockStainedGlass)getRegisteredBlock("stained_glass");
        this._stained_glass_pane = (BlockStainedGlassPane)getRegisteredBlock("stained_glass_pane");
        this._prismarine = getRegisteredBlock("prismarine");
        this._sea_lantern = getRegisteredBlock("sea_lantern");
        this._standing_banner = getRegisteredBlock("standing_banner");
        this._wall_banner = getRegisteredBlock("wall_banner");
        this._red_sandstone = getRegisteredBlock("red_sandstone");
        this._red_sandstone_stairs = getRegisteredBlock("red_sandstone_stairs");
        this._double_stone_slab2 = (BlockSlab)getRegisteredBlock("double_stone_slab2");
        this._stone_slab2 = (BlockSlab)getRegisteredBlock("stone_slab2");
        
    }
    */
}
